name: Update gallery.json from Dropbox

on:
  schedule:
    - cron: "*/5 * * * *"  # รันทุก 5 นาที
  workflow_dispatch:        # สามารถกดรันเองได้

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: public/dropbox-gallery

      - name: Run Dropbox script
        run: node dropbox-gallery.js
        working-directory: public/dropbox-gallery
        env:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/gallery.json
          git diff --cached --quiet || git commit -m "🔄 Update gallery.json from Dropbox"
          git push